main: net.amoebaman.kitmaster.KitMaster

name: KitMaster
version: 1.3.2
author: AmoebaMan
website: www.amoebaman.net
description: The complete short-term kit plugin
softdepend: [Vault]

commands:

  kit:
    description: Get a kit
    usage: /kit <kit-name>
    permission-message: You don't have permission to take kits via command

  givekit:
    description: Give a kit to a player
    usage: /givekit <player> <kit-name>
    permission: kitmaster.give
    permission-message: You dont have permission to give kits

  kitlist:
    description: List the available kits
    usage: /kitlist
    permission: kitmaster.list
    permission-message: You don't have permission to view kits

  kitinfo:
    description: Displays info about a kit
    usage: /kitinfo <kit>
    permission: kitmaster.info
    permission-message: You don't have permissions to get info about kits

  reloadkits:
    description: Reloads kits from kits.yml
    usage: /reloadkits
    permission: kitmaster.reload
    permission-message: You don't have permission to reload kits
    
  itemmeta:
    aliases: [meta, metadata]
    description: Base for various item metadata manipulation commands
    usage: /itemmeta ...
    permission: kitmaster.meta
    permission-message: You don't have permission to manage item metadata
    
##  editkit:
##    aliases: [kitedit, kedit, editk]
##    description: Base for various kit editing commands
##    usage: /editkit ...
##    permission: kitmaster.edit
##    permission-message: You don't have permission to edit kits
    
  inventory-kit:
    aliases: [inventorykit, inv-kit, invkit]
    description: Forms a basic kit using the contents of the player's inventory
    usage: /inventory-kit <name>
    permission: kitmaster.edit
    permission-message: You don't have permission to create kits

permissions:

  kitmaster.*:
    description: Gives access to all SuperKits permissions
    children:
      kitmaster.give: true
      kitmaster.reload: true
      kitmaster.kit.*: true
      kitmaster.notimeout: true
      kitmaster.nocharge: true
      kitmaster.createsign: true
      kitmaster.meta: true
      kitmaster.edit: true
    
  kitmaster.give:
    description: Allows the player to give kits to other players
    default: op
    
  kitmaster.reload:
    description: Allows the player to reload the kits file
    default: op
    
  kitmaster.kit.*:
    description: Grants permission for all kits
    default: op
    
  kitmaster.notimeout:
    description: Removes the timeouts of all kits entirely for the player
    default: op
    
  kitmaster.nocharge:
    description: Removes any economic costs/grants from kits for the player
    default: op
    
  kitmaster.createsign:
    description: Allows the player to create and break kit selection signs
    default: op
    
  kitmaster.meta:
    description: Allows the player to manage item metadata
    default: op
    
  kitmaster.edit:
    description: Allows the player to edit kits
    default: op
    